FROM node:20-alpine AS builder

RUN apk add --no-cache openssl

WORKDIR /app

ARG NEXTAUTH_URL
ARG NEXT_PUBLIC_MAPBOX_TOKEN

ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXT_PUBLIC_MAPBOX_TOKEN=$NEXT_PUBLIC_MAPBOX_TOKEN

COPY web/package.json web/package-lock.json ./
RUN npm i --legacy-peer-deps

COPY web/ .

RUN --mount=type=secret,id=auth_secret \

    --mount=type=secret,id=supabase_url \
    --mount=type=secret,id=supabase_key \
    AUTH_SECRET="$(cat /run/secrets/auth_secret)" \

    SUPABASE_URL="$(cat /run/secrets/supabase_url)" \
    SUPABASE_KEY="$(cat /run/secrets/supabase_key)" \
    npm run build

FROM node:20-alpine AS runner

RUN apk add --no-cache openssl

WORKDIR /app

ENV NODE_ENV=production
ENV HOSTNAME="0.0.0.0"
ENV PORT=3000

RUN addgroup -g 1001 appuser && \
    adduser -D -u 1001 -G appuser appuser

COPY --from=builder --chown=appuser:appuser /app/.next/standalone ./
COPY --from=builder --chown=appuser:appuser /app/.next/static ./.next/static
COPY --from=builder --chown=appuser:appuser /app/public ./public

USER appuser

EXPOSE 3000

CMD ["npm", "start"]
